namespace: new-team-test
resources:
  - namespace.yaml
  - rbac.yaml
  - psp.yaml
bases:
  - ../../flux/
patchesStrategicMerge:
  - flux-patch.yaml
configMapGenerator:
  - name: flux-kube-config
    behavior: replace
    files:
      - kubeconfig.yaml
